### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by sali123** [citp/OpenWPM#186]
Error 404 Not Found when trying to read about content_policy_Type column by clicking the below link

https://searchfox.org/mozilla-central/source/dom/base/nsIContentPolicyBase.idl

I am clicking on the above link from the following page
https://github.com/citp/OpenWPM/wiki/Instrumentation-Schema-Documentation

**Comment by englehardt** [comment]
Thanks! It looks like this file was removed with a refactor. The new link is `https://searchfox.org/mozilla-central/source/dom/base/nsIContentPolicy.idl`.

Ideally we should include our own type map so the column stores a string rather than an integer. See the TODO [here](https://github.com/citp/OpenWPM/blob/7ee14e3bff2d14ec4f41aab9a6530908b8745d74/automation/Extension/firefox/lib/http-instrument.js#L232).
