### ISSUE TITLE
install OpenWPM Extension on FFesr52

### ISSUE THREAD

**Issue by sali123** [citp/OpenWPM#194]
I installed openwpm on ubuntu 16.04. 

I removed my firefox installation. I installed firefox-52.0.1esr release. set xpinstall.signatures.required = false. disabled auto update. then installed openwpm.xpi as extension to my FF 52Esr browser.

I opened FF, browsed several websites, but the openwpm did not create sqllite file that contains the visited pages, http traffic, cookies, javascript etc..

please advice. I need to use your extension in an important project to gather javascript script_url, func_name, script_loc_eval, operation, value during a certain user registration process . This is cannot be automated using openWPM task manager since the registration process has multiple steps. 

Note: I installed FourthParty extension on the same machine. it is working fine I am able to see the fourthparty.sqlite in FF profile directory.

**Comment by sali123** [comment]
when I opened the console after accessing https://outlook.live.com/owa/ the following appeared

Property descriptor not found for window.navigator getBattery Navigator { permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "unspecified", oscpu: "Linux x86_64", vendor: "", vendorSub: "", productSub: "20100101", cookieEnabled: true, buildID: "20170316213902", 17 more… }  owa:461:9
Successfully started all instrumentation.  owa:635:5
Property descriptor not found for window.navigator getBattery Navigator { permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "unspecified", oscpu: "Linux x86_64", vendor: "", vendorSub: "", productSub: "20100101", cookieEnabled: true, buildID: "20170316213902", 17 more… }  a3698060313.html:461:9
Successfully started all instrumentation.  a3698060313.html:635:5
Strict-Transport-Security: The site specified a header that could not be parsed successfully.[Learn More] prefetch.aspx
Property descriptor not found for window.navigator getBattery Navigator { permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "unspecified", oscpu: "Linux x86_64", vendor: "", vendorSub: "", productSub: "20100101", cookieEnabled: true, buildID: "20170316213902", 17 more… }  prefetch.aspx:461:9
Successfully started all instrumentation.  prefetch.aspx:635:5

**Comment by englehardt** [comment]
The OpenWPM extension was not meant to run as a standalone extension, so you won't see any sqlite files unless you run the entire platform. You could revert the functionality to match that of FourthParty. Start with code from FourthParty's [logging-db.js](https://github.com/fourthparty/fourthparty/blob/master/extension/lib/logging-db.js), updating parts of the `open`, `close`, `executeSQL`, and `createInsert` methods of OpenWPM's [version](https://github.com/citp/OpenWPM/blob/master/automation/Extension/firefox/lib/loggingdb.js). You'll likely have to do some massaging to merge the two, since OpenWPM's schema expects some additional columns like `visit_id`.

Alternatively, you could do a quick hack for your use case. When you call `CommandSequence::get` pass a `sleep` argument (and `timeout`) set to a very large value. Be sure you aren't running things in headless mode. Then, when you run the script OpenWPM will start up, visit the site, and start sleeping. You can then manually interact with the site after that and close the browser when you're done.

**Comment by englehardt** [comment]
Also, I recommend updating to the newest OpenWPM version. The error you're seeing in the console was fixed by https://github.com/citp/OpenWPM/commit/86ca05f1b485cd1c47eacc2e97df2131be37fe5b.
