### ISSUE TITLE
Javascript instrumentation breaks functionality

### ISSUE THREAD

**Issue by englehardt** [citp/OpenWPM#7]
Javascript instrumentation in the most recent release of FourthParty is broken. I've attempted to fix and expand upon it (see `automation/Extension/firefox/lib/javascript-instrument.js`) while porting the code, with some success. 

I found it possible to monitor certain things, such as canvas and localStorage, by intercepting calls and property updates on the prototype objects. This works well for method calls, but causes property updates to fail to apply which can very easily break the functionality of the object being instrumented.

For example, setting fonts / colors for canvas rendering contexts will fail to apply when the instrumentation is enabled.

**Comment by ghostwords** [comment]
It seems the problem is that while the [setter](https://github.com/citp/OpenWPM/blob/be122690d5f4ea78c5eec6a64b5468a59e659ae4/automation/Extension/firefox/data/content.js#L258-L261) we define on any given CanvasRenderingContext2D.prototype property does intercept all attempts to set that property on an instantiated CanvasRenderingContext2D object, the setter doesn't have any access to the instance object's actual property. The instance object's property never gets the update, which matters since then the browser doesn't know about any updates to, say, a canvas element.

**Comment by englehardt** [comment]
The fix ended up being very simple (though it took me a while to figure it out). Rather than keeping an extra variable around to hold a pointer to the original property, we can just access the property though `this` when a `get` or `set` of that property is called. This means we won't need to access the property until the object is initialized, so it will work for both native objects like `window.navigator` and for native prototypes like `window.HTMLCanvasElement.prototype`.

See: https://github.com/citp/OpenWPM/blob/master/automation/Extension/firefox/data/content.js#L286-L301
