### ISSUE TITLE
The requests that get answered with 304 no modified are never stored in the DB

### ISSUE THREAD

**Issue by akatsukle** [citp/OpenWPM#70]
The requests that get answered with 304 are never logged by OpenWPM. 
We can't find any traces of them nor in the http_requests table nor in the http_responses table.
How to reproduce :
Access a static website (for example : www.example.com) twice.

NB : For a static website, the second access is never logged by OpenWPM. However if we try to access a website that is dynamic (eg. www.google.com), some requests will still be displayed when the website is accessed for the second time.

Here is a configuration file that can be used to reproduce the bug, and a dump of the database after I runned it on my computer.
[ex.txt](https://github.com/citp/OpenWPM/files/227302/ex.txt)
[dumpdb.txt](https://github.com/citp/OpenWPM/files/227303/dumpdb.txt)

**Comment by dreisman** [comment]
Thanks for pointing this out. It looks like the issue isn't with 304s. You aren't seeing the second request to example.com because the browser isn't even making a network request, but is grabbing the page from an in-memory cache (so it never goes through the proxy that logs requests).

We will probably change in the future how requests are collected so that in-browser cache hits aren't missed, but for now I recommend you set the firefox preferences 'browser.cache.disk.enable' and 'browser.cache.memory.enable' to false in https://github.com/citp/OpenWPM/blob/master/automation/DeployBrowsers/deploy_firefox.py. This will force your browser to make the network request, and then you should start to actually see the 304s.

**Comment by akatsukle** [comment]
I didn't know that a request was being made to the server only when an user actually press reload, and not everytime the page is displaying again. Thank you, and for the suggestion it actually helped me a lot. :)
