### ISSUE TITLE
OpenWPM can't be installed with Firefox 48+ release version

### ISSUE THREAD

**Issue by gunesacar** [citp/OpenWPM#92]
Firefox 48+ won't allow unsigned extensions to be installed, with no override through `xpinstall.signatures.required` preference.

https://wiki.mozilla.org/Add-ons/Extension_Signing#Timeline

An alternative is to use the developer edition for the crawls, which does not require extensions to be signed.

**Comment by englehardt** [comment]
We can also use [unbranded builds](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) as long as we confirm that the only change branding.

**Comment by englehardt** [comment]
A second issue with 48+ is e10s compatibility. Our add-on will require a few updates, see:

https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK

**Comment by englehardt** [comment]
#152 moved us to FF52. Extension signing and multiprocess requirements don't seem to be an issue yet. The browser just provides a warning that our extension shouldn't be trusted since it isn't signed. e10s is disabled since our extension isn't compatible, but that's fine.

e10s compatibility will be a concern for the next ESR, FF 59. We will need to update to that version by June 26th, 2018, when support is ended for FF 52 ESR ([timeline here](https://www.mozilla.org/en-US/firefox/organizations/faq/)]. Since FF57 drops support for add-on-sdk-based extensions, we will likely need to make a number of changes to continue to use our instrumentation. Let's track those in #148.
